spring:
  config:
    activate:
      on-profile: local

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL_LOCAL}
    username: ${SPRING_DATASOURCE_USERNAME_LOCAL}
    password: ${SPRING_DATASOURCE_PASSWORD_LOCAL}

  data:
    redis:
      host: ${REDIS_HOST_LOCAL}
      port: ${REDIS_PORT_LOCAL}
      password: ${REDIS_PASSWORD_LOCAL}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true

  mail:
    host: ${MAIL_HOST_LOCAL}
    port: ${MAIL_PORT_LOCAL}
    username: ${MAIL_USERNAME_LOCAL}
    password: ${MAIL_PASSWORD_LOCAL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.harusari.chainware

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha